### ISSUE TITLE
Multisession outputs seem off after DerivativesDataSink refactor

### ISSUE THREAD

**Issue by oesteban** [poldracklab/smriprep#191]
After processing ds114 I only have outputs for one session, where I think I'd expect the outputs not to have any session except for the timepoint-to-template transforms. Is that expectation okay?

/cc @effigies

**Comment by oesteban** [comment]
This is the output, with ``--output-spaces MNI152NLin2009cAsym fsaverage:den-10k fsaverage6``:
```
derivatives/smriprep/desc-aparcaseg_dseg.tsv
derivatives/smriprep/desc-aseg_dseg.tsv
derivatives/smriprep/sub-01.html
derivatives/smriprep/dataset_description.json
derivatives/smriprep/sub-01
derivatives/smriprep/sub-01/ses-retest
derivatives/smriprep/sub-01/ses-retest/anat
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-L_pial.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-L_inflated.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_label-WM_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_desc-brain_mask.json
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-brain_mask.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-brain_mask.json
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_dseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_dseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_from-fsnative_to-T1w_mode-image_xfm.txt
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-R_pial.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_label-GM_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-R_smoothwm.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-aseg_dseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-preproc_T1w.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-L_midthickness.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-aparcaseg_dseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_label-CSF_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-L_smoothwm.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-R_midthickness.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_from-T1w_to-fsnative_mode-image_xfm.txt
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_hemi-R_inflated.surf.gii
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_desc-preproc_T1w.json
derivatives/smriprep/sub-01/ses-retest/anat/sub-01_ses-retest_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
```

Digging deeper, I realized that we are getting this familiar error that explains the missing `from/to-orig` files:

```
Node: _ds_t1w_ref_xfms1
Working directory: /home/oesteban/tmp/fmriprep-ds114/work/smriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_derivatives_wf/ds_t1w_ref_xfms/mapflow/_ds_t1w_ref_xfms1

Node inputs:

acquisition = <undefined>
atlas = <undefined>
base_directory = /home/oesteban/tmp/fmriprep-ds114/derivatives
ceagent = <undefined>
check_hdr = True
cohort = <undefined>
compress = <undefined>
data_dtype = <undefined>
datatype = <undefined>
density = <undefined>
desc = <undefined>
direction = <undefined>
dismiss_entities = <undefined>
echo = <undefined>
extension = <undefined>
fmap = <undefined>
from = orig
hemi = <undefined>
in_file = ['/home/oesteban/tmp/fmriprep-ds114/work/smriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_template_wf/concat_xfms/mapflow/_concat_xfms1/out_inv.tfm']
label = <undefined>
meta_dict = <undefined>
modality = <undefined>
mode = image
model = <undefined>
proc = <undefined>
reconstruction = <undefined>
recording = <undefined>
resolution = <undefined>
roi = <undefined>
run = <undefined>
scans = <undefined>
roi = <undefined>
run = <undefined>
scans = <undefined>
scans = <undefined>
session = <undefined>
source_file = /oak/stanford/groups/russpold/data/openfmri/ds000114/sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz
space = <undefined>
subject = <undefined>
subset = <undefined>
suffix = xfm
task = <undefined>
to = T1w

Traceback (most recent call last):
  File "/home/oesteban/workspace/nipype/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/oesteban/workspace/nipype/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/bids.py", line 501, in _run_interface
    raise ValueError(f"Could not build path with entities {out_entities}.")
ValueError: Could not build path with entities {'subject': '01', 'session': 'test', 'suffix': 'xfm', 'datatype': 'anat', 'extension': 'tfm', 'from': 'orig', 'mode': 'image', 'to': 'T1w'}.
```

I will send a fix to #188 shortly.

But the question of dropping the session is still there.
